para_root/account_sys/urls.py
from django.urls import path
from . import views
app_name="account_sys"
urlpatterns = [

    path('register', views.register_page,name="register"),
    path('login', views.login_page,name="login"),
    path('log_out', views.log_out,name="logout"),
    path('profile', views.profile,name="profile"),
    path('change_password', views.change_password,name="change_password"),
    path('profile_photo', views.profile_photo,name="profile_photo"),
]

para_root/para_root/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('accounts/',include("account_sys.urls")),
    path('posts/', include("post.urls")),
]
urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

para_root/post/urls.py
from django.urls import path
from . import views
app_name='post'
urlpatterns = [
    path('', views.post_list_view,name="list"),
    path('search', views.search,name="search"),
    path('tag/<slug>', views.tag,name="tag"),
    path('create', views.post_create,name="create"),
    path('create_form', views.create_form,name="create_form"),
    path('edit/<pk>', views.edit,name="edit"),
    path('delete/<pk>', views.delete,name="delete"),

    path('<slug>', views.post_detail_view,name="detail"),

]

para_root/account_sys/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserPhoto(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_photo=models.ImageField(blank=True,null=True,upload_to="")
    def __str__(self):
        return self.user.username

para_root/account_sys/views.py
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.http import Http404
from django.shortcuts import render, redirect
from . import models
from django.contrib.auth.hashers import make_password,check_password


# Create your views here.
def register_page(request):
    if request.method == "POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        re_password=request.POST.get("re_password")
        if password == re_password:
            User.objects.create_user(username=username,password=password)
        else: raise Http404("pass word doesnot match")

    context={}
    return render(request,"account_sys/register_page.html",context)




def login_page(request):
    if request.method == "POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(request,username=username,password=password)
        login(request,user)



    context={}
    return render(request,"account_sys/login_page.html",context)





def log_out(request):
    logout(request)
    return redirect("/")




def profile(request):
    username=request.user.username
    user=User.objects.get(username=username)
    profile=models.UserPhoto.objects.filter(user=user).exists()
    if profile:

        userphoto= models.UserPhoto.objects.filter(user=user).first()

        aks=userphoto.profile_photo
        if aks is not None:
            context = {
                "aks": aks
            }
    else:
        context={

            }





    return render(request, "account_sys/profile.html", context)






def change_password(request):
    req_user=request.user.username
    user=User.objects.get(username=req_user)
    user_main_password=user.password
    if request.method=="POST":
        old_password=request.POST.get("your_old_password")
        new_password=request.POST.get("your_new_password")
        confirm_new_password=request.POST.get("confirm")
        check=check_password(old_password,user_main_password)
        is_eq=new_password==confirm_new_password

        if (check) and (is_eq):
            new_hashed=make_password(new_password)
            user.password=new_hashed
            user.save()
        else:raise Http404("something wentwrong")

    context={}
    return render(request, "account_sys/change_password.html", context)




def profile_photo(request):
    if request.method=="POST":
        aks=request.FILES.get("photo")
        user=request.user
        userphoto=models.UserPhoto.objects.filter(user=user).exists()
        if userphoto:
            main_class=models.UserPhoto.objects.get(user=user)
            main_class.profile_photo=aks
            main_class.save()
        else:
            models.UserPhoto.objects.create(user=user,profile_photo=aks)




    context={}
    return render(request, "account_sys/change_profile_photo.html", context)

para_root/account_sys/templates/account_sys/change_password.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
<div class="container">

    <form method="post">
    <br>    {% csrf_token %}
   <br><div class="col-6">     <input class="form-control" type="password" placeholder="your old password" name="your_old_password">
        <br>
        <input class="form-control" type="password" placeholder="your new password" name="your_new_password">
        <br>
        <input class="form-control" type="password" placeholder="confirm your new password" name="confirm">
        <br>
        <input type="submit" value="change">
    </div>
    </form>
</div>
    
    

{%  endblock  %}

para_root/account_sys/templates/account_sys/change_profile_photo.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
<div class="container">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="file" name="photo">
        <br>

        <br>
        <input type="submit" value="set">




    </form>







</div>



{%  endblock  %}

para_root/account_sys/templates/account_sys/login_page.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
<div class="container">

    <form  method="post">
        {% csrf_token %}

<div class="col-6">
    <br>
        <input class="form-control" type="text" name="username" placeholder="username">
        <br>

        <input class="form-control" type="password" name="password" placeholder="password">
        <br>


        <input class="form-control" type="submit" value="login">


</div>









    </form>





</div>



{%  endblock  %}

para_root/account_sys/templates/account_sys/profile.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
<div class="container">

{% if aks %}
        <img  style="height:300px; width:300px " src="{{aks.url}}" alt="">
    {% endif %}
<li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:change_password' %}">changeyour password <span class="sr-only">(current)</span></a>
      </li >
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:profile_photo' %}">changeyour profile photo <span class="sr-only">(current)</span></a>
      </li >






</div>
    
    

{%  endblock  %}

para_root/account_sys/templates/account_sys/register_page.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
<div class="container">

    <form  method="post">
        {% csrf_token %}

<div class="col-6">
    <br>
        <input class="form-control" type="text" name="username" placeholder="username">
        <br>

        <input class="form-control" type="password" name="password" placeholder="password">
        <br>
        <input class="form-control" type="password" name="re_password" placeholder="re_password">
        <br>
        <input class="form-control" type="submit" value="register">


</div>









    </form>





</div>

{%  endblock  %}