para_root/para_root/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('accounts/',include("account_sys.urls")),
    path('posts/', include("post.urls")),
]
urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

para_root/post/urls.py
from django.urls import path
from . import views
app_name='post'
urlpatterns = [
    path('', views.post_list_view,name="list"),
    path('search', views.search,name="search"),
    path('tag/<slug>', views.tag,name="tag"),
    path('create', views.post_create,name="create"),
    path('create_form', views.create_form,name="create_form"),
    path('edit/<pk>', views.edit,name="edit"),
    path('delete/<pk>', views.delete,name="delete"),

    path('<slug>', views.post_detail_view,name="detail"),

]

para_root/post/models.py
from django.contrib.auth.models import User
from django.db import models
import os
import random
from django.db.models import Q

from django.core.validators import MaxValueValidator, MinValueValidator

from .utils import unique_slug_generator
from django.db.models.signals import pre_save

from my_tag.models import Tag

#########################manager#####################################################
class PostManager(models.Manager):
    def active_posts(self):
        return self.get_queryset().filter(active=True)
    def get_by_slug(self,slug):
        qs=self.get_queryset().filter(active=True,slug=slug)
        if qs.count() == 1:
            return qs
        else:
            return None
    def search(self,q):
        lookup = Q(title__icontains=q) | Q(body__icontains = q) | Q(my_tags__title__icontains=q)
        return self.get_queryset().filter(lookup,active=True).distinct()



#################################image_url_maker##################################################

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_name = random.randint(1, 27634723542)
    name, ext = get_filename_ext(filename)
    # final_name = f"{new_name}{ext}"
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/{final_name}"
###############Class main model#####################################################################################
class Post(models.Model):
    title=models.CharField(max_length=150,unique=True)
    slug=models.SlugField(blank=True, unique=True)
    body=models.TextField()
    image=models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    active=models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)
    publisher = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    count=models.IntegerField(default=1,validators=[MaxValueValidator(10)])

    my_tags=models.ManyToManyField(Tag,blank=True)
    objects=PostManager()
    class Meta:
        verbose_name = 'مطلب'
        verbose_name_plural = 'مطالب'

    def __str__(self):
        return self.title










#############################################slug########################################
def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Post)

############################count==0##################baraye false kardan activ agar tedad az 1 kamtar shode
def post_pre_save_count(sender, instance, *args, **kwargs):
    if instance.count==0:
        instance.active=False

pre_save.connect(post_pre_save_count, sender=Post)

para_root/post/forms.py
from django import forms
from . import models
class create_post_form(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=["title","slug","body","image","active","count",'my_tags']

para_root/post/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from .models import Post

from .forms import create_post_form
from django.contrib.auth.decorators import permission_required
from my_tag.models import Tag
from django.contrib import messages

# Create your views here.
################postlist##############################################################
def post_list_view(request):
    qs=models.Post.objects.active_posts().order_by("-time")

    context={
        "title":"posts",
        "posts":qs,

    }
    return render(request, "post/post_list_view.html", context)


class Bazdid:
    adadesh=0
###################post detail#######################################################
def post_detail_view(request,slug):


    detail_qs=models.Post.objects.get_by_slug(slug=slug)

######FOR TAGS
    my_post=Post.objects.filter(slug=slug)
    ####inja post ro gerfetam rokhr\tam to aliaqa
    aliaqa=list(my_post)[0]
    ####tamamtag haye poste ro gereftam
    tags_to_page=list(aliaqa.my_tags.all())




    context={
        "post":detail_qs,
        "tags_to_page":tags_to_page,
    }

    if detail_qs is None:
        raise Http404()

    Bazdid.adadesh+=1
    ####baraye kam shodan tedad bad az kharid
    if Bazdid.adadesh>2:
        me = models.Post.objects.get(slug=slug)
        me.count -= 1
        me.save()

    return render(request,"post/post_detail_view.html",context)

########create post#############################################################
def post_create(request):

    if request.method=="POST":
        title=request.POST.get("title")
        my_tags=request.POST.get("my_tag")
        splited=my_tags.split(",")
        body=request.POST.get("body")
        image=request._files.get("image")
        publisher=request.user
        active=request.POST.get("active")
        if active == "on":
            active=True
        else:active=False
        count=request.POST.get("count")
        count=int(count)
        Post.objects.create(title=title, body=body, active=active, count=count, publisher=publisher, image=image)
        thispost = Post.objects.get(title=title)
        list_tags_id=[]
        for i in splited:
            Tag.objects.create(title=i)
            this_tag=Tag.objects.get(title=i)
            list_tags_id.append(this_tag.id)


        for t in list_tags_id:
            thispost.my_tags.add(t)















    return render(request, "post/post_create.html", {})
################crate built in forms#######################################################
def create_form(request):
    create__form=create_post_form(request.POST,request.FILES )

    if create__form.is_valid():
        instance=create__form.save(commit=False)
        instance.publisher=request.user
        instance.save()
    else:create__form=create_post_form()
    context={
        "create_post_form":create__form

    }
    return render(request, "post/create_form.html",context)

####################edit##########################
def edit(request,pk):
    qs=get_object_or_404(Post, pk=pk)

    if request.method=="POST":
        form=create_post_form(request.POST,request.FILES,instance=qs)

        if form.is_valid():
            form.save()
    else:
        form=create_post_form(instance=qs)
    context={
        "form":form,
        'post':qs
    }

    return render(request, "post/post_edit.html",context)


####################delete##########################
@permission_required("blog.delete_post","log_in",raise_exception=True)
def delete(request,pk):
    qs=get_object_or_404(Post, pk=pk)

    if request.method=="POST":
        form=create_post_form(request.POST,instance=qs)

        if form.is_valid():
            qs.delete()
            return redirect("post:list")
    else:
        form=create_post_form(instance=qs)
    context={
        "form":form,
        'post':qs
    }

    return render(request, "post/post_delete.html",context)



##############################################search############################3


def search(request):
    q=request.GET.get("q")
    if q is not None:

       post=Post.objects.search(q)
    else:
        post=Post.objects.active_posts()

    context={
        "posts":post
    }

    return render(request,"post/search.html",context)

#################tag##############################
###in func mibare besafhe ii ke post hayy k on tago drn neshoon mide
def tag(request,slug):
    tag_get=Tag.objects.get(slug=slug)

    qs = models.Post.objects.filter(active=True, my_tags=tag_get)





    context={
        "posts":qs
    }
    return render(request,"post/post_list_view.html",context)

para_root/post/templates/post/create_form.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}









{% block  content %}
    <div class="container">


        <form action="" method="post" ENCTYPE="multipart/form-data">
            
            
            {% csrf_token %}
            {{ create_post_form}}
            <input type="submit">
        </form>


    </div>

{%  endblock  %}

para_root/post/templates/post/post_create.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}






{% block  content %}
    <div class="container">



<form action="{% url "post:create" %}" method="post" name="create_form" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="text " name="title " placeholder="title">
    <br><br>
    <input type="textarea" name=" body" placeholder="body" class="vLargeTextField">
    <br><br>
    <input type="file" name="image" placeholder="image">
    <br><br>
    active:
    <input type="checkbox" name="active" placeholder="active">
    <br><br>

    <input type="number" name="count" placeholder="count">
    <br><br>

    <input type="text" placeholder="tags" name="my_tag">
    <br><br>
    <input type="submit">




</form>


    </div>

{%  endblock  %}

para_root/post/templates/post/post_delete.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}



{% block  content %}
    <div class="container">
<div> are sure you want to delete {{ post.title }}</div>
<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div hidden> {{ form }}</div>
    <input type="submit" value="yes" class="btn btn-danger">
    <a href="{% url 'post:list' %}" class="btn-info btn"> no</a>




</form>


    </div>

{%  endblock  %}

para_root/post/templates/post/post_detail_view.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}
{% block  content %}
    <div class="container">
    {% for item in post %}
    <div class="bg-success">
        <div class="bg-secondary">{{ item.title }} </div>
       {% if item.image %}  <img src="{{ item.image.url }}" alt="" style="width: 150px;height: 150px" >{% endif %}
        <div>{{ item.body  }} </div>
        <div>{{ item.time | timesince}} </div>
        <div>{{ item.time | date}} </div>
        <div> publisher: {{ item.publisher  }} </div>
{#    {% for tagss in item.my_tags %}#}
{#        taggs#}
{#    {% endfor %}#}

        <a href="{% url 'post:edit' pk=item.pk %}" class="btn-info btn"> edit</a>
        <a href="{% url 'post:delete' pk=item.pk %}" class="btn-danger btn"> delete</a>



    </div>
    {% endfor %}
{#    برای برچسب ها#}
    <div>
    <p> برچسب ها</p>
    {% for tags in tags_to_page %}
        <a href="{% url 'post:tag' slug=tags.slug   %}">{{ tags }}</a>
    {% endfor %}

    </div>
    </div>


{%  endblock  %}

para_root/post/templates/post/post_edit.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ title }}</title>
{%  endblock  %}



{% block  content %}
    <div class="container">

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit">




</form>


    </div>

{%  endblock  %}

para_root/post/templates/post/post_list_view.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ post.title }}</title>
{%  endblock  %}
{% block  content %}
    <div class="container">
    {% for post in posts %}

<div class="bg-success " >

            <div class="bg-info">{{ post.title }} </div>
  {% if post.image %}       <img src="{{ post.image.url }}" alt="" style="width: 150px;height: 150px" >{% endif %}
        <div >{{ post.body | truncatewords:10 }} </div>
        <div > {{ post.time | timesince}} </div>
        <div >{{ post.time | date}} </div>
        <div > publisher: {{ post.publisher  }} </div>


    <br>
        <a href="{% url "post:detail" slug=post.slug %}"class="btn-danger"> read more</a>








    </div>
    {% endfor %}


    </div>
{%  endblock  %}

para_root/post/templates/post/search.html
{% extends "shared/base.html" %}

{% block  title %}
    <title>{{ post.title }}</title>
{%  endblock  %}
{% block  content %}
    <div class="container">
    {% for post in posts %}

<div class="bg-success " >

            <div class="bg-info">{{ post.title }} </div>
  {% if post.image %}       <img src="{{ post.image.url }}" alt="" style="width: 150px;height: 150px" >{% endif %}
        <div >{{ post.body | truncatewords:10 }} </div>
        <div > {{ post.time | timesince}} </div>
        <div >{{ post.time | date}} </div>
        <div > publisher: {{ post.publisher  }} </div>


    <br>
        <a href="{% url "post:detail" slug=post.slug %}"class="btn-danger"> read more</a>








    </div>
    {% endfor %}


    </div>
{%  endblock  %}