para_root/account_sys/urls.py
from django.urls import path
from . import views
app_name="account_sys"
urlpatterns = [

    path('register', views.register_page,name="register"),
    path('login', views.login_page,name="login"),
    path('log_out', views.log_out,name="logout"),
    path('profile', views.profile,name="profile"),
    path('change_password', views.change_password,name="change_password"),
    path('profile_photo', views.profile_photo,name="profile_photo"),
]

para_root/para_root/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('accounts/',include("account_sys.urls")),
    path('posts/', include("post.urls")),
]
urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

para_root/post/urls.py
from django.urls import path
from . import views
app_name='post'
urlpatterns = [
    path('', views.post_list_view,name="list"),
    path('search', views.search,name="search"),
    path('tag/<slug>', views.tag,name="tag"),
    path('create', views.post_create,name="create"),
    path('create_form', views.create_form,name="create_form"),
    path('edit/<pk>', views.edit,name="edit"),
    path('delete/<pk>', views.delete,name="delete"),

    path('<slug>', views.post_detail_view,name="detail"),

]

para_root/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>
<body >
{% include "shared/nav.html" %}
<div style="min-height: 550px ">
{% block content %}

{% endblock %}
</div>
<div class="footer">     {% include 'shared/footer.html' %}</div>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>

para_root/templates/shared/footer.html
<nav class="navbar navbar-expand-lg navbar-light  bg-dark">
<div  style="color: white; text-align:right">
    <p> این سایت توسط علی لطفی ساخته شده</p>
    <br>
<p> هدف ساخت بکند منظم و با کد نویسی بهینه است نه کار کردن روی فرانت و ظاهر سایت و این طاهر فقط برای نشان دادن قابلیت های سایت است </p>
  <br>

      <br>
</div>
</nav>

para_root/templates/shared/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark" >


  <a class="navbar-brand" href="{% url 'home' %}">PARAIBA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div  class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav"  >

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li >
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:register' %}">register <span class="sr-only">(current)</span></a>
      </li >
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:login' %}">login <span class="sr-only">(current)</span></a>
      </li >
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:logout' %}">logout <span class="sr-only">(current)</span></a>
      </li >
     <li class="nav-item active">
        <a class="nav-link" href="{% url 'account_sys:profile' %}">profile <span class="sr-only">(current)</span></a>
      </li >
           <li class="nav-item">
        <a class="nav-link" href="{% url 'post:list' %}">posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'post:create' %}">create post </a>
      </li>


    </ul>



  </div>
    {% if user.is_authenticated %}
        <div style="color:white"> {{ user.username }}</div>

    {% endif %}
</nav>
     <div style="background-color: #447e9b">
         <form action="{% url "post:search" %}"  method="get">

            <input type="text" placeholder="search" value="{{ request.GET.q }}"name="q">


         </form>  </div>